//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 12.0
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using System.Windows;
using HalconDotNet;

public partial class HDevelopExportDisp
{
    public HTuple hv_ExpDefaultWinHandle;
    HTuple w = 0, h = 0,pointer_, type_;
    // Main procedure 
    private void action(HObject ho_Image)
    {
        //HOperatorSet.GenEmptyObj(out ho_Image);
        try
        {
            //HOperatorSet.SetDraw(hv_ExpDefaultWinHandle,"margin");
            HOperatorSet.GetImagePointer1(ho_Image, out pointer_, out type_, out w, out h);
            HOperatorSet.SetPart(hv_ExpDefaultWinHandle,0,0,h,w);
            HOperatorSet.DispObj(ho_Image, hv_ExpDefaultWinHandle);
        }catch(HalconException HDevExpDefaultException)
        {
            ho_Image.Dispose();
            throw HDevExpDefaultException;
        }
    }

    public void InitHalcon(int width = 512, int height = 512)
    {
        // Default settings used in HDevelop 
        HOperatorSet.SetSystem("width", width);
        HOperatorSet.SetSystem("height", height);
    }

    public void RunHalcon(HTuple Window, HObject ho_Image)
    {
        try
        {
            hv_ExpDefaultWinHandle = Window;
            action(ho_Image);
        }
        catch (HalconException e)
        {
            throw e;
        }
    }

}

