//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 12.0
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using HalconDotNet;

public partial class HDevelopExportGrab
{
    public HDevelopExportGrab(String UID)
    {
        UserID = UID;
    }
  // public HTuple hv_ExpDefaultWinHandle;
  private HTuple hv_AcqHandle = null;
  private String UserID = "A"; 
  // Main procedure 
  private void action(String UID)
  {
   // HTuple hv_exception = new HTuple();
    // Initialize local and output iconic variables 
    //HOperatorSet.GenEmptyObj(out ho_Image);
    try
    {
      //Image Acquisition 01: Attention: The initialization may fail in case parameters need to
      //Image Acquisition 01: be set in a specific order (e.g., image resolution vs. offset).
      HOperatorSet.OpenFramegrabber("GigEVision", 0, 0, 0, 0, 0, 0, "default", -1, 
          "default", -1, "false", "default", UID, 0, -1, out hv_AcqHandle);
      HOperatorSet.SetFramegrabberParam(hv_AcqHandle, "ExposureTime", 50000);
      HOperatorSet.SetFramegrabberParam(hv_AcqHandle, "Gain", 0);
     // HOperatorSet.SetFramegrabberParam(hv_AcqHandle, "TriggerMode", "On");
            HOperatorSet.SetFramegrabberParam(hv_AcqHandle, "TriggerMode", "Off");
            HOperatorSet.SetFramegrabberParam(hv_AcqHandle, "TriggerSource", "Line0");
      HOperatorSet.SetFramegrabberParam(hv_AcqHandle, "TriggerActivation", "RisingEdge");
      HOperatorSet.GrabImageStart(hv_AcqHandle, -1);
      return;
    }
    catch (HalconException HDevExpDefaultException)
    {
      throw HDevExpDefaultException;
    }


  }

  public void InitHalcon(String str_UserID = "A")
  {
        try
        {
            action(str_UserID);
        }
        catch (HalconException ex)
        {
            throw ex;
        }
  }

    public void Grab(out HObject ho_Image)
    {
        try
        {
            ho_Image = null;
            HOperatorSet.GenEmptyObj(out ho_Image);
            ho_Image.Dispose();
            HOperatorSet.GrabImageAsync(out ho_Image, hv_AcqHandle, 1000);
        }
        catch (HalconException HDevExpDefaultException)
        {
            throw HDevExpDefaultException;
        }
    }

    public void Grab(out HObject ho_Image, out HTuple hv_exception) {
        hv_exception = null;
        ho_Image = null;
        try
        {
            
            HOperatorSet.GenEmptyObj(out ho_Image);
            ho_Image.Dispose();
            HOperatorSet.GrabImageAsync(out ho_Image, hv_AcqHandle, 1000);
        }
        catch (HalconException HDevExpDefaultException1)
        {
            HDevExpDefaultException1.ToHTuple(out hv_exception);
            throw HDevExpDefaultException1;
        }
    }

  public void RunHalcon()
  {
     
        //action();
        //HOperatorSet.CloseFramegrabber(hv_AcqHandle);
    }

}

